<h1>from sklearn import linear_model</h1>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

<h1>Create DataFrame</h1>

In [9]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

<h1>Make DataFrame Series into two dimensional numpy array</h1>

In [10]:
area = df.iloc[:, :-1].values
price = df.iloc[:, 1].values

<h1>Create an object of LinearRegression Class and, Fit the data</h1>

In [11]:
reg_model = linear_model.LinearRegression()
reg_model.fit(area, price)

LinearRegression()

<h1>Make a prediction of a random 2D area value

In [13]:
reg_model.predict([[3300]])

array([628715.75342466])

<h1>Pickle</h1>

<h3>Save Model</h3>

In [14]:
import pickle

In [15]:
with open('model_pickle', 'wb') as f:
    pickle.dump(reg_model, f)

<h3>Load Model</h3>

In [17]:
with open('model_pickle', 'rb') as f:
    reg_model_pkl = pickle.load(f)

<h3>Predict</h3>

In [22]:
reg_model_pkl.predict([[3300]])

array([628715.75342466])

<h1>Joblib</h1>

In [20]:
import joblib

<h3>Save Model</h3>

In [23]:
joblib.dump(reg_model, 'model_joblib')

['model_joblib']

<h3>Load Model</h3>

In [24]:
reg_model_joblib = joblib.load('model_joblib')

<h3>Predict</h3>

In [25]:
reg_model_joblib.predict([[3300]])

array([628715.75342466])